import Head from "next/head";
import styles from "@/styles/Home.module.sass";
import { useEffect, useRef, useState } from "react";

const areas = [
  { className: 'area1', image: 'https://picsum.photos/1200/1200/?1', title: '頁面1', blockText: '1' },
  { className: 'area2', image: 'https://picsum.photos/1200/1200/?2', title: '頁面2', blockText: '2' },
  { className: 'area3', image: 'https://picsum.photos/1200/1200/?3', title: '頁面3', blockText: '3' },
  { className: 'area4', image: 'https://picsum.photos/1200/1200/?4', title: '頁面4', blockText: '4' },
  { className: 'area5', image: 'https://picsum.photos/1200/1200/?5', title: '頁面5', blockText: '5' },
  { className: 'area6', image: 'https://picsum.photos/1200/1200/?6', title: '頁面6', blockText: '6' }
];

export default function Home() {
  const [activeArea, setActiveArea] = useState(1);
  const scrollTimeoutRef = useRef(null);

  const getArea = () => {
    let currentArea = null;
    const areas = document.querySelectorAll(`.${styles.area}`);
    areas.forEach((area, index) => {
      const rect = area.getBoundingClientRect();
      if (rect.left <= window.innerWidth / 2 && rect.right > window.innerWidth / 2){
        currentArea = index + 1;
      }
    });
    return currentArea;
  };

  const onMainScroll = e => {
    setActiveArea(null)
    clearTimeout(scrollTimeoutRef.current);
    scrollTimeoutRef.current = setTimeout(() => {
      const area = getArea();
      if (area) {
        setActiveArea(area);
      }
    }, 200);
  }
  
  return (
    <>
      <Head>
        <title>橫向捲軸頁面與捲動事件</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main onScroll={onMainScroll} className={styles.main}>
        {areas.map((area, index) => (
          <div
            key={index}
            className={`${styles.area} ${styles[area.className]} ${activeArea === index + 1 ? styles.active : ''}`}
            data-image={area.image}
            data-title={area.title}
          >
            <div className={styles.photo} style={{ backgroundImage: `url(${area.image})` }}></div>
            <div className={styles.text}>{area.title}</div>
          </div>
        ))}
      </main>
    </>
  );
}
